import type { Metadata } from "next";
import { Geist, Geist_Mono, Host_Grotesk } from "next/font/google";
import { ReactLenis } from "lenis/react";
import "./globals.css";
import { ConvexClientProvider } from "@/shared/components/providers/convex-client-provider";
import StoreProvider from "@/shared/components/providers/store-provider";
import { Toast } from "@/shared/components/ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hostGrotesk = Host_Grotesk({
  variable: "--font-host",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${hostGrotesk.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ConvexClientProvider>
          <StoreProvider>
            <ReactLenis root />
            {children}
            <Toast />
          </StoreProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
